name: Compile Docker Images

on:
  push:
    tags:
      - '*'
jobs:
  build-image:
    name: Builds the docker image
    runs-on: ubuntu-latest # run the job on the newly created runner 
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            jonzky/debug-helium-miner
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=
            type=sha,format=long,prefix=

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .        
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/debug-helium-miner:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/debug-helium-miner:buildcache,mode=max
          build-args: |
            VERSION=${{steps.tag.outputs.tag}}
            EXTRA_BUILD_APK_PACKAGES=apk-tools
            EXTRA_RUNNER_APK_PACKAGES=apk-tools
            BUILDER_IMAGE=arm64v8/erlang:24-alpine
            RUNNER_IMAGE=arm64v8/alpine:3.15
            REBAR_BUILD_TARGET=docker
            BUILD_NET=mainnet

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}